### ISSUE TITLE
wait-for-heartbeat.js can hang indefinitely

### ISSUE THREAD

**Issue by wagmarcel** [Open-IoT-Service-Platform/oisp-frontend#124] opened 2019-04-11 07:06 UTC
https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/20f51daa6511218ee1d9c6a5f51e0c9a961c0469/public-interface/scripts/wait-for-heartbeat.js#L74

@oguzcankirmemis, I am not sure but I observed that the startup hangs at this point sometimes.
I suspect that once this point is reached, the script will not terminate, because the kafka listeners are setup already. At the same time, there is no way to retry because it is only called once with timeout.
Wouldn't it be better if you'd listen to events from  kafkaOffset? Then, even if this point is reached, there will be later events if something new arrives.
Can you please review this issue and let me know what you think?

**Comment by oguzcankirmemis** [comment] 2019-04-18 01:02
@wagmarcel, you are right, if the script reaches this point, it certainly will not terminate. Though, the problem is that I can't produce a scenario in which the program reaches this point. In my opinion, it should not be possible for it to reach this point because if a topic is not created then it throws an error and tries to get offset again, if the topic is created however the minimum offset it can get is actually 0. Therefore it should not be possible to reach this point, if the fetchLatestOffset succeeds/fails. So correct me if am wrong whether a scenario exists that fetchLatestOffset can have negative return value.

For the event listening, fetchLatestOffset automatically listens on the 'ready' event of the kafkaOffset, and kafkaOffset as far as I know the only other event it emits is 'connect', which is the event that says a broker is ready. I am not sure if this would bring anything. See [here](https://github.com/SOHU-Co/kafka-node#offset), for the events that kafkaOffset emits.

**Comment by wagmarcel** [comment] 2019-04-18 07:28
@oguzcankirmemis  I can confirm that this state is reached. I have seen  several times frontend hanging with the last statement "Cannnot get Kafka offset".
I agree, it should not be reached. But it is reached :-) . In 1 of hundred launches... so not very often but often enough to be annoying ...

**Comment by oguzcankirmemis** [comment] 2019-05-22 02:14
Solved after #134, closing...

**Closed as completed by oguzcankirmemis** 2019-05-22 02:14 UTC
Labels: bug
