### ISSUE TITLE
Admin users are unable to post device data unless Device_ID==GATEWAY_ID

### ISSUE THREAD

**Issue by srware** [Open-IoT-Service-Platform/oisp-frontend#82] opened 2018-12-20 10:19 UTC
Admins should be able to post device data without any restrictions. Currently there is a check in place which means that "users" can only post device data if the device ID and gateway ID are equal which makes no sense.

https://github.com/Open-IoT-Service-Platform/oisp-frontend/blob/20f51daa6511218ee1d9c6a5f51e0c9a961c0469/public-interface/engine/api/v1/data.js#L43

We should also add a test case for this into the E2E tests.

Thanks

**Comment by wagmarcel** [comment] 2018-12-30 23:12
@oguzcankirmemis, I looked at this in another context (I wanted to submit the dataType of the samples to the backend to allow different handling dependent of dataType)
In this context I had to rewrite the data.sending and (hopefully) simplified it.
It is my first draft but please take a look at my branch and let me know whether the direction is ok.
https://github.com/wagmarcel/oisp-frontend/tree/provide-dataType-to-backend

**Comment by wagmarcel** [comment] 2019-01-01 12:31
I think I understood  why device data sending and user data sending needs different treatments.
Assuming that the submit path is the heavily used API in a system, this is the path which needs to be optimized most. Therefore, the database lookups are minimized, in principle it is only checked whether the componentIDs belong to the Device (not whether the device belongs to the account!). In case of a device-token, the deviceID and the accountID are  included in the token, so no check is needed whether the device belongs to the account. However, in a user-token, there is no deviceID, only the userID and the accountIDs which the user has the right to access. Therefore, it is not checked whether the DeviceID the user tries to write data to is part of the account!
But still, I think the above check does not make sense. It would be better to add additional DB lookup in case a user tries to write data. Since this is not the default case, the additional DB lookup does not hurt the performance so much. So right approach is to check whether the token is not a device token, and in case it is a user-token to check whether the device belongs to the account.
The decision whether admin or user can do this should be configured in the auth module, simply by allowing or forbidding a user to use the path.
I will implement it and create a PR.

**Comment by srware** [comment] 2019-01-02 11:35
@wagmarcel agree with all of your points. We should maybe write a recommendation or optimisation notice in the SDK and other relevant places to highlight that this API method shouldn't be used for frequent data submissions, only testing or special cases.

**Comment by arkocal** [comment] 2019-01-04 09:03
I think this was designed to *force* users to make use of device tokens, but I agree with @srware about updating the documentation. Account tokens are impractical for such use cases from the lazy programmers perspective anyway, as they expire very fast.

**Comment by oguzcankirmemis** [comment] 2019-01-08 00:23
@wagmarcel I looked at your branch (at 3rd of January, could not quickly reply because of connection problems back then). I think it suits with what we need (especially it really is much simpler than what we already have), un my opinion we should change to this version soon, after it is finished of course. I expect that our data send unit tests will fail with these changes, but It should not be hard for me to readjust them so it fits to this and we can have more solid opinion whether the functionality is satisfying our needs. Great work!

**Comment by arkocal** [comment] 2019-01-08 08:30
@oguzcankirmemis @wagmarcel Does that effect the API regarding external access in anyway?

**Comment by wagmarcel** [comment] 2019-01-08 18:56
@arkocal, I don't think so.

**Comment by arkocal** [comment] 2019-02-04 15:29
The expected behavior is changed now, closing. We should update the documentation, but we should go through the whole documentation anyway.

**Closed as completed by arkocal** 2019-02-04 15:29 UTC
